[workspace]
repo_url = "https://github.com/ghillb/swarmux"
git_only = true
publish = false
changelog_update = false
git_release_enable = true
git_tag_enable = true
git_tag_name = "v{{ version }}"
git_release_name = "v{{ version }}"
git_release_type = "prod"
git_release_latest = true
pr_branch_prefix = "release-plz-"
pr_labels = ["release"]
pr_name = "chore: release v{{ version }}"
release_always = false
release_commits = "^(feat|fix|perf|refactor)(\\(.+\\))?!?:"
semver_check = false
